<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\EngineeringPlayground.Outbox.Domain\EngineeringPlayground.Outbox.Domain.csproj" />
    <ProjectReference Include="..\EngineeringPlayground.Outbox.Infrastructure\EngineeringPlayground.Outbox.Infrastructure.csproj" />
  </ItemGroup>

</Project>
